In [14]:
import arpes.config
from arpes.io import example_data
dataarray_cut2 = example_data.cut2.spectrum

Activating auto-logging. Current session state plus future input saved.
Filename       : logs/Untitled2_2024-06-21_06-03-05.log
Mode           : backup
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [15]:
from arpes.plotting import stack_plot

In [18]:
an_iterator = dataarray_cut2.G.iter_coords("phi")

In [19]:
first_coord = next(an_iterator)

In [20]:
first_coord

{'phi': np.float64(-0.2178031280148764)}

In [26]:
ys0 = stack_plot._y_shifted(offset_correction="zero", coord_value=first_coord["phi"],
                      marginal=dataarray_cut2.sel(first_coord),
                      scale_parameters=(1, 10, False)
                    )

In [27]:
ys0[:5]

array([-0.09820913, -0.15604263, -0.14532103, -0.16914233, -0.11608813])

In [28]:
ys0 = stack_plot._y_shifted(offset_correction="zero", coord_value=first_coord["phi"],
                      marginal=dataarray_cut2.sel(first_coord),
                      scale_parameters=(1, 10, False)
                    )

In [29]:
ys0[:5]

array([-0.09820913, -0.15604263, -0.14532103, -0.16914233, -0.11608813])

In [30]:
ys1 =       stack_plot._y_shifted(
            offset_correction="constant",
            coord_value=first_coord["phi"],
            marginal=dataarray_cut2.sel(first_coord),
            scale_parameters=(1, 10, False))


In [31]:
ys1[:5]

array([-0.21780313, -0.27563663, -0.26491503, -0.28873633, -0.23568213])

In [32]:
ys2 =       stack_plot._y_shifted(
            offset_correction="constant_right",
            coord_value=first_coord["phi"],
            marginal=dataarray_cut2.sel(first_coord),
            scale_parameters=(1, 10, False))


In [33]:
ys2[:5]

array([-0.09820913, -0.15604263, -0.14532103, -0.16914233, -0.11608813])